In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("C:/Users/user/Documents/data science/practice/WHO dataset/Life Expectancy Data.csv")
df =pd.DataFrame(data)

In [3]:
df.head(5)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [4]:
df.shape

(2938, 22)

In [5]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [7]:
data.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score

In [10]:
status_dict = {'Developing': 0,'Developed': 1}

df.Status = [status_dict[item] for item in df.Status]
df['Status'].value_counts()

Status
0    2426
1     512
Name: count, dtype: int64

In [11]:
df["Life expectancy "] = df["Life expectancy "].replace(np.NaN, df["Life expectancy "].mean())
df["infant deaths"] = df["infant deaths"].replace(np.NaN, df["infant deaths"].median())
df["Adult Mortality"] = df["Adult Mortality"].replace(np.NaN, df["Adult Mortality"].median())
df["Alcohol"] = df["Alcohol"].replace(np.NaN, df["Alcohol"].median())
df["Hepatitis B"] = df["Hepatitis B"].replace(np.NaN, df["Hepatitis B"].median())
df[" BMI "] = df[" BMI "].replace(np.NaN, df[" BMI "].mean())
df["Polio"] = df["Polio"].replace(np.NaN, df["Polio"].mean())
df["Total expenditure"] = df["Total expenditure"].replace(np.NaN, df["Total expenditure"].mean())
df["Diphtheria "] = df["Diphtheria "].replace(np.NaN, df["Diphtheria "].mean())
df["GDP"] = df["GDP"].replace(np.NaN, df["GDP"].median())
df[" thinness  1-19 years"] = df[" thinness  1-19 years"].replace(np.NaN, df[" thinness  1-19 years"].median())
df[" thinness 5-9 years"] = df[" thinness 5-9 years"].replace(np.NaN, df[" thinness 5-9 years"].median())
df["Income composition of resources"] = df["Income composition of resources"].replace(np.NaN, df["Income composition of resources"].median())
df["Schooling"] = df["Schooling"].replace(np.NaN, df["Schooling"].median())
df["Population"] = df["Population"].replace(np.NaN, df["Population"].mean())

In [12]:
df.drop(['Country'],axis=1,inplace=True)

In [13]:
X = df.drop(['Life expectancy '],axis=1)
y = df['Life expectancy ']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
#reg = LinearRegression().fit(X, y)

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [16]:
#reg.score(X, y)

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

0.8194669771128726

In [17]:
#y_predicted = reg.predict(X_test)

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [19]:
#y_predicted

array([67.1086707 , 77.28417361, 75.41241343, 78.00304224, 46.84640521,
       50.35030191, 67.55916196, 70.55259003, 74.52571026, 54.7221624 ,
       51.8684456 , 63.72992028, 64.83733395, 70.46116215, 70.61776913,
       62.81847448, 56.13654405, 80.92755947, 68.73433958, 81.68407697,
       81.72646152, 84.35196394, 70.67534105, 69.05064602, 69.58466154,
       68.24204113, 60.90591505, 61.97020969, 78.3870618 , 71.56589602,
       65.84541463, 75.2665567 , 69.508077  , 68.73737085, 80.8264716 ,
       57.96897174, 66.6984688 , 72.87626639, 62.84246727, 76.22882122,
       57.53779112, 64.00800543, 75.0308906 , 81.32631861, 75.9076861 ,
       57.22213714, 79.37930824, 70.33805359, 65.93312469, 67.45237334,
       57.9126831 , 61.31642066, 78.30248483, 72.42387304, 73.1171758 ,
       59.62181339, 75.67479002, 70.03293074, 66.52718579, 69.10574539,
       78.16704082, 54.68153951, 73.8956454 , 69.66050503, 52.46849225,
       52.70081084, 53.51413387, 80.03107578, 58.73581207, 77.44066783,
       80.49853777, 75.27694527, 73.80155474, 60.40275376, 56.14494196,
       70.68246449, 63.95602561, 76.88861496, 56.59366243, 62.90911046,
       63.97689144, 61.41835859, 67.24577804, 68.04131611, 59.19623661,
       74.73191155, 75.13712965, 68.2686562 , 76.3289701 , 75.99354282,
       73.07600172, 62.7794122 , 72.55344336, 77.38597768, 74.12122999,
       68.29215876, 79.05858262, 71.38267242, 66.68851272, 61.37554346,
       83.54602909, 55.92673089, 72.39209912, 53.76621033, 74.22438   ,
       77.92823182, 71.06737013, 66.75677663, 65.01574152, 64.51967868,
       68.88428842, 61.94102278, 50.00377371, 70.21944865, 62.96136774,
       76.92511375, 63.73766192, 56.80584041, 65.19490273, 63.89733049,
       65.27399111, 71.69133032, 80.624707  , 62.94962153, 58.79958462,
       65.95640246, 70.87106497, 64.70188943, 72.94980974, 71.37937925,
       75.12268432, 80.74385761, 59.43991227, 69.449334  , 54.38358343,
       69.7549609 , 75.27866698, 77.41126381, 75.6043428 , 76.5318399 ,
       69.16429125, 65.43240445, 61.66934259, 59.23781112, 58.90232138,
       64.38967145, 59.23233228, 74.91065415, 63.58759141, 75.87512911,
       79.47698624, 80.76960792, 69.7447754 , 71.18048243, 80.99656017,
       77.60677267, 80.91525384, 73.4099569 , 80.5589393 , 78.85557228,
       73.08633788, 79.52850249, 70.10801742, 78.1855233 , 67.27491233,
       63.45731528, 64.82977065, 80.59483792, 76.97968071, 74.8633924 ,
       81.44621875, 71.76635746, 67.83254479, 61.07737333, 71.19523652,
       64.15333785, 69.85577437, 63.71437165, 60.38412138, 71.09800032,
       83.21451486, 67.98575796, 83.4553092 , 73.5639106 , 78.94971336,
       35.77662222, 61.01747518, 42.9003042 , 72.67557391, 73.01661782,
       64.36668119, 68.08267355, 81.32041528, 62.84245672, 75.85556074,
       67.42757388, 72.62797375, 68.25005455, 79.60010817, 73.30409995,
       73.32325867, 56.99616546, 73.16178163, 71.35521205, 67.38505695,
       49.36591658, 74.76143332, 68.04488688, 71.12468663, 82.78698387,
       60.24504522, 61.34475573, 73.1613088 , 51.85180936, 53.67968335,
       58.13591514, 60.83335742, 73.76299348, 62.2910166 , 66.94209768,
       77.59604387, 74.42756008, 69.64777119, 79.87330459, 77.57752665,
       50.96079947, 56.72206146, 74.31448324, 54.73655706, 63.18503795,
       69.73022702, 72.58259867, 61.45862602, 73.69482328, 72.67089463,
       53.69467107, 77.63651383, 78.27062518, 49.52223278, 71.73135271,
       76.56148867, 69.42493254, 72.61773929, 71.43820991, 63.6796419 ,
       53.54851897, 82.84394957, 76.16939619, 76.46833638, 62.24011286,
       69.90099833, 75.44707333, 58.04744071, 78.85177919, 69.92458359,
       71.85331539, 62.43045814, 79.75470775, 58.34849834, 51.45414995,
       68.46976119, 72.88237001, 61.03965149, 55.55143041, 68.69838454,
       79.62545349, 68.7284474 , 81.60301845, 58.6231709 , 61.07991539,
       55.6084513 , 50.79630237, 69.62145724, 70.76306938, 54.41115553,
       72.50517883, 59.61639805, 73.74209384, 64.72518688, 64.34589807,
       68.70924404, 80.70805545, 59.72421956, 75.85102364, 76.01409288,
       64.59729233, 78.41590112, 46.45784894, 61.04320967, 76.36659454,
       66.27107945, 69.20920062, 68.51194384, 72.90302724, 74.27051451,
       63.68529379, 78.79632508, 71.56654827, 54.48464179, 73.38373354,
       73.89185979, 76.26903552, 69.2874066 , 74.44747255, 72.70405909,
       57.17673153, 58.05502724, 50.13113785, 68.97381582, 75.34302754,
       72.46951726, 60.70227878, 75.07730046, 64.36352716, 69.28012249,
       66.17400279, 54.05239933, 70.92166009, 55.59054866, 71.84318815,
       51.719116  , 78.22075377, 56.27174152, 70.13448034, 69.69814265,
       76.57909378, 75.86181089, 70.80626611, 72.11961694, 81.93971701,
       73.50672042, 69.02922387, 68.14165266, 69.39540049, 74.73274977,
       81.31352815, 72.86144175, 76.84190933, 68.8385233 , 71.46975305,
       70.37079107, 74.75404838, 72.19498337, 74.24247737, 70.14442955,
       50.16327486, 65.87097975, 73.26905073, 74.38365343, 74.92624393,
       62.97293953, 69.48703242, 59.17807917, 59.15806593, 72.94475101,
       79.8221342 , 70.35082041, 61.1113166 , 70.3941274 , 73.78391   ,
       62.87383879, 73.49172938, 76.65972466, 68.26097449, 65.78348642,
       63.32309344, 60.66078695, 75.27434976, 63.43082054, 75.03981112,
       72.62909604, 55.76449043, 73.06378401, 78.10267326, 74.30783376,
       72.87698668, 58.14505954, 69.78880875, 70.99739421, 65.65759153,
       60.64969652, 81.6825421 , 81.04628377, 80.07975751, 62.99080316,
       55.14901268, 74.86634505, 56.31316788, 70.98637417, 76.20675065,
       48.93432767, 79.26607785, 77.02973187, 80.52270809, 64.63964042,
       66.42126355, 79.2206161 , 69.95746391, 79.56709123, 71.90808744,
       53.44039895, 75.87264487, 50.23877129, 72.21480741, 65.61852969,
       63.31547451, 68.87242476, 73.69284915, 67.44089754, 73.22085474,
       71.69666587, 81.8694704 , 72.75561101, 75.47646154, 70.74620714,
       69.28418334, 59.53506606, 70.50813071, 69.11794936, 64.82048237,
       63.89388318, 60.54221778, 70.61637665, 73.34757471, 73.34598245,
       71.19688647, 65.38696795, 64.40899727, 73.51895731, 74.56657655,
       54.40186785, 75.74765629, 74.25030138, 66.96665588, 34.83173529,
       64.94914033, 56.39736565, 68.00807891, 66.84446886, 72.99631492,
       75.0419566 , 69.76643709, 71.14642809, 78.58230887, 77.86288369,
       70.26258458, 76.66895468, 78.43303384, 84.98549137, 57.39174229,
       82.33360455, 56.01835159, 69.79238279, 73.13449748, 52.26504938,
       76.31269535, 84.04823475, 51.89763016, 66.87601166, 76.65198005,
       73.39194601, 70.08328929, 61.6268316 , 66.39627734, 64.16778545,
       57.48730418, 78.92759371, 71.32062376, 79.94023898, 69.72779599,
       68.23476528, 76.43787434, 74.25987404, 71.19272566, 82.73693056,
       71.03340384, 67.06343192, 69.51237757, 80.94480308, 71.3874164 ,
       75.18704015, 70.97185534, 70.52823859, 76.13312115, 69.49566007,
       82.27375744, 77.8633043 , 80.08261647, 71.76993112, 73.85519021,
       73.86179884, 74.58084854, 49.80321672, 70.50459909, 74.78435434,
       62.4711324 , 79.95440426, 72.07042631, 61.78126398, 72.54818839,
       74.39709993, 58.30188142, 80.21820839, 70.8327707 , 76.80948375,
       78.55942471, 69.14777217, 81.89852519, 75.18332787, 70.28719892,
       65.09556184, 68.22855932, 68.95786457, 73.19728075, 48.39991964,
       65.40895561, 63.2344833 , 64.05197194, 65.61718506, 59.41370934,
       73.94023406, 77.55624512, 72.03974693, 73.06495236, 67.92236021,
       63.56957142, 66.2922507 , 70.92645428, 76.11871469, 81.35858625,
       56.99446242, 72.29576806, 69.28248874, 79.1061873 , 66.19119415,
       79.09061965, 70.40098164, 78.70482714, 82.20116655, 82.44130906,
       79.94296401, 48.47605042, 64.56408374, 67.8923262 , 75.36648726,
       64.19153519, 70.44998902, 61.53917369, 63.74950719, 69.60276969,
       77.75053594, 56.69151116, 79.41169451, 60.40157412, 74.32007127,
       67.39431419, 77.88466851, 68.01037406, 70.76632969, 78.31887044,
       65.97865347, 82.77019819, 84.6526446 , 75.43597078, 51.48087348,
       75.56210707, 77.89613654, 84.27247338, 59.10917345, 72.51502502,
       73.78214091, 63.22158778, 78.47563167, 68.64338587, 74.6236612 ,
       65.62769257, 68.82813542, 71.44824556, 61.49960354, 76.02024599,
       54.03768765, 78.33512901, 81.36682463, 58.77793981, 76.45854156,
       63.78067762, 70.21176549, 73.58873691])

In [22]:
model_1 = LinearRegression()
model_1.fit(X_train, y_train)

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

LinearRegression()

In [23]:
y_pred_1 = model_1.predict(X_test)
pred_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_1})
pred_df.head()

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

      Actual  Predicted
2546    73.7  67.142280
650     75.9  77.288115
1740    74.2  75.672019
177     76.8  78.054046
1377    51.9  46.887005

In [25]:
#from sklearn.metrics import r2_score
 
#print("Accuracy score of the predictions: {0}".format(r2_score(y_test, y_pred_1)))
#Acc.append(r2_score(y_test, y_pred_1))

In [20]:
from sklearn import metrics

In [21]:
mae = metrics.mean_absolute_error(y_test, y_predicted)
mse = metrics.mean_squared_error(y_test, y_predicted)
r2 = metrics.r2_score(y_test, y_predicted)

print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))

The model performance for testing set
--------------------------------------
MAE is 2.8348303496360527
MSE is 14.943091053856683
R2 score is 0.8275172471621879